test:pylint:
  image: python:3.9
  before_script:
    - python -V # Print out python version for debugging
  script:
    - pip install pylint --quiet
    - pip install pyyaml
    - pylint --ignored-classes=_socketobject --max-line-length=150 *.py

test:pytest:
  image: python:3.9
  before_script:
    - python -V # Print out python version for debugging
  script:
    - pip install pytest --quiet
    - pip install pyyaml
    - pip install graphviz
    - python -m pytest
    - apt-get update && apt-get install graphviz

