stages:
  -PEP8
  -unittest

test:PEP8:
    image: python:3.6
    script:
        - pip install pylint --quiet
        - pylint --ignored-classes=_socketobject *.py
test:unittest:
  image: python:3.6
  script:
    - pip install pytest --quiet
    - python -m pytest
