build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CI_REGISTRY/group/project/image:latest .
    - docker push $CI_REGISTRY/group/project/image:latest
test:pylint:
  stage: test
  image: python:3.9
  before_script:
    - python -V # Print out python version for debugging
  script:
    - pip install pylint --quiet
    - pip install pyyaml
    - pylint --ignored-classes=_socketobject --max-line-length=150 --max-statements=50 *.py

test:pytest:
  image: python:3.9
  stage : test
  before_script:
    - python -V # Print out python version for debugging
  script:
    - pip install pytest --quiet
    - pip install pyyaml
    - pip install graphviz
    - apt-get update && apt-get upgrade -y graphviz
    - python -m pytest
    

