image: "python:3.7"

before_script:
  - python --version

stages:
  - Static Analysis
  - Test

pylint:
  stage: Static Analysis
  script:
  - pip install pylint --quiet
  - pylint -d C0301 src/*.py

pytest:
  stage: Test
  script:
  - pip install pytest --quiet 
  - cd test/;pytest -v
