stages:
  -Static analysis
  -unittest

pylint:
    stage: Static analysis
    image: python:3.6
    script:
        - pip install pylint --quiet
        - pylint --ignored-classes=_socketobject *.py
pytest:
  stage: unittest
  image: python:3.6
  script:
    - pip install pytest --quiet
    - python -m pytest
