image: node:latest

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
    - pages

test:pylint:
  image: python:3.9
  before_script:
    - python -V # Print out python version for debugging
  script:
    - pip install pylint --quiet
    - pip install pyyaml
    - pip install ruamel.yaml
    - pylint --ignored-classes=_socketobject --max-line-length=150 --max-statements=50 *.py

test:pytest:
  image: python:3.9
  before_script:
    - python -V # Print out python version for debugging
  script:
    - pip install pytest --quiet
    - pip install pyyaml
    - pip install ruamel.yaml
    - pip install graphviz
    - apt-get update && apt-get upgrade -y graphviz
    - python -m pytest

build-package:
  stage: deploy
  image: python:3.9
  script:
    - cat $PYPIRC > /tmp/.pypirc
    - pip install -U twine setuptools build
    - python -m build
    - python -m twine upload -r testpypi dist/* --config-file /tmp/.pypirc
 
