test:pylint:
    image: python:3.9
    before_script:
      - python -V # Print out python version for debugging
    script:
        - pip install pylint --quiet
        - pylint --ignored-classes=_socketobject --max-line-length=150 *.py


test:pytest:
  image: python:3.9
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  cache:
    paths:
      - .cache/pip
      - venv/

  before_script:
    - python -V               # Print out python version for debugging
    - python -m venv venv
    - source venv/bin/activate
    - pip install requests
    - pip install pdoc3 pytest pytest-cov pytest-html

  tests:
    script:
      - python -m pytest --cov=netzwerkprogrammierung --cov-report html --html=report.html --self-contained-html tests
    artifacts:
      paths:
        - htmlcov
        - report.html

  pages:
    script:
      - pdoc3 --html --output-dir public netzwerkprogrammierung
    artifacts:
      paths:
        - public
