default:
  # Default output type
  std_type: ".svg"
  # Default level of Detail // 1 = least detail, 2 = medium detail, 3 = most detail
  std_details: 1
  # Open in browser after the diagram is built, True or False
  open_in_browser: False