# This module is automatically generated by autogen.sh. DO NOT EDIT.
from . import _ICONS


class _Vrt_Light_LightPng(_ICONS):
    _type = "VRT_Light_LightPng"
    _icon_dir = "../resources/icons/VRT_Icons/VRT_LightPng/VRT_light_LightPng"


class DLaserScanner1LightPng(_Vrt_Light_LightPng):
    _icon = "2dlaserscanner1.png"
class DLaserScanner2LightPng(_Vrt_Light_LightPng):
    _icon = "2d laser scanner 2.png"
class DLaserScanner1LightPng(_Vrt_Light_LightPng):
    _icon = "3d laser scanner 1.png"
# class 3D Laser Scanner2LightPng(_Vrt_Light_LightPng):
#     _icon = "3d laser scanner 2.png"
# class AegisDatacellCellularDatalogger1LightPng(_Vrt_Light_LightPng):
#     _icon = "aegis datacell cellular datalogger 1.png"
# class AllenBradley Controllogix PlcLightPng(_Vrt_Light_LightPng):
#     _icon = "allen-bradley controllogix plc.png"
# class AllenBradley Flexio 1LightPng(_Vrt_Light_LightPng):
#     _icon = "allen-bradley flexio 1.png"
# class AllenBradley Flexio 2LightPng(_Vrt_Light_LightPng):
#     _icon = "allen-bradley flexio 2.png"
# class Appliance 1LightPng(_Vrt_Light_LightPng):
#     _icon = "appliance 1.png"
# class Atm Switch 1LightPng(_Vrt_Light_LightPng):
#     _icon = "atm switch 1.png"
# class Atm Switch 2LightPng(_Vrt_Light_LightPng):
#     _icon = "atm switch 2.png"
# class Authentication Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "authentication server 1.png"
# class Branch Feeder MonitorLightPng(_Vrt_Light_LightPng):
#     _icon = "branch feeder monitor.png"
# class Cctv Camera 1LightPng(_Vrt_Light_LightPng):
#     _icon = "cctv camera 1.png"
# class Cctv Camera 3LightPng(_Vrt_Light_LightPng):
#     _icon = "cctv camera 3.png"
# class Cet MultiCircuit Power Monitor LightPng(Mcpm)LightPng(_Vrt_Light_LightPng):
#     _icon = "cet multi-circuit power monitor LightPng(mcpm).png"
# class Communications ServerLightPng(_Vrt_Light_LightPng):
#     _icon = "communications server.png"
# class Compact Plc 1LightPng(_Vrt_Light_LightPng):
#     _icon = "compact plc 1.png"
# class Coronis Wavenis LightPng(Waveflow Wavelog Wavetalk Mesh Mote)LightPng(_Vrt_Light_LightPng):
#     _icon = "coronis wavenis LightPng(waveflow wavelog wavetalk mesh mote).png"
# class Coronis Wavenis LightPng(Waveport Mesh Base Station)LightPng(_Vrt_Light_LightPng):
#     _icon = "coronis wavenis LightPng(waveport mesh base station).png"
# class Current Transformer StripLightPng(_Vrt_Light_LightPng):
#     _icon = "current transformer strip.png"
# class Data Acquisition LightPng(Scada) Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "data acquisition LightPng(scada) server 1.png"
# class Data Logger Rtu 1LightPng(_Vrt_Light_LightPng):
#     _icon = "data logger rtu 1.png"
# class Database Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "database server 1.png"
# class Desktop 1LightPng(_Vrt_Light_LightPng):
#     _icon = "desktop 1.png"
# class Desktop 3LightPng(_Vrt_Light_LightPng):
#     _icon = "desktop 3.png"
# class DialUp Modem 1LightPng(_Vrt_Light_LightPng):
#     _icon = "dial-up modem 1.png"
# class Directory Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "directory server 1.png"
# class Directory ServerLightPng(_Vrt_Light_LightPng):
#     _icon = "directory server.png"
# class Document Scanner 1LightPng(_Vrt_Light_LightPng):
#     _icon = "document scanner 1.png"
# class Document Scanner 3LightPng(_Vrt_Light_LightPng):
#     _icon = "document scanner 3.png"
# class Document Scanner 5LightPng(_Vrt_Light_LightPng):
#     _icon = "document scanner 5.png"
# class Document Scanner 7LightPng(_Vrt_Light_LightPng):
#     _icon = "document scanner 7.png"
# class End Users 1LightPng(_Vrt_Light_LightPng):
#     _icon = "end users 1.png"
# class Energy Utility MeterLightPng(_Vrt_Light_LightPng):
#     _icon = "energy utility meter.png"
# class Facsimile 1LightPng(_Vrt_Light_LightPng):
#     _icon = "facsimile 1.png"
# class Facsimile 3LightPng(_Vrt_Light_LightPng):
#     _icon = "facsimile 3.png"
# class Fibre Optic BreakOut Tray 1LightPng(_Vrt_Light_LightPng):
#     _icon = "fibre optic break-out tray 1.png"
# class File Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "file server 1.png"
# class Firewall 1LightPng(_Vrt_Light_LightPng):
#     _icon = "firewall 1.png"
# class Firewall 2LightPng(_Vrt_Light_LightPng):
#     _icon = "firewall 2.png"
# class Flat Panel Display 1LightPng(_Vrt_Light_LightPng):
#     _icon = "flat panel display 1.png"
# class Gas MeterLightPng(_Vrt_Light_LightPng):
#     _icon = "gas meter.png"
# class Generic Black Box 1LightPng(_Vrt_Light_LightPng):
#     _icon = "generic black box 1.png"
# class Generic Plc Dcs Controller 1LightPng(_Vrt_Light_LightPng):
#     _icon = "generic plc dcs controller 1.png"
# class Hub 1LightPng(_Vrt_Light_LightPng):
#     _icon = "hub 1.png"
# class Hub 2LightPng(_Vrt_Light_LightPng):
#     _icon = "hub 2.png"
# class Industrial Barcode Scanner 1LightPng(_Vrt_Light_LightPng):
#     _icon = "industrial barcode scanner 1.png"
# class Industrial Barcode Scanner 3LightPng(_Vrt_Light_LightPng):
#     _icon = "industrial barcode scanner 3.png"
# class Industrial Cellular Modem 1LightPng(_Vrt_Light_LightPng):
#     _icon = "industrial cellular modem 1.png"
# class Industrial Cellular Modem 3LightPng(_Vrt_Light_LightPng):
#     _icon = "industrial cellular modem 3.png"
# class Industrial Ethernet To Serial Converter 1LightPng(_Vrt_Light_LightPng):
#     _icon = "industrial ethernet to serial converter 1.png"
# class Industrial Fibre To Ethernet Converter 1LightPng(_Vrt_Light_LightPng):
#     _icon = "industrial fibre to ethernet converter 1.png"
# class Industrial Pc 1LightPng(_Vrt_Light_LightPng):
#     _icon = "industrial pc 1.png"
# class Industrial Pc 3LightPng(_Vrt_Light_LightPng):
#     _icon = "industrial pc 3.png"
# class Industrial Switch 1LightPng(_Vrt_Light_LightPng):
#     _icon = "industrial switch 1.png"
# class Inkjet Printer 1LightPng(_Vrt_Light_LightPng):
#     _icon = "inkjet printer 1.png"
# class Inkjet Printer 3LightPng(_Vrt_Light_LightPng):
#     _icon = "inkjet printer 3.png"
# class Laptop 1LightPng(_Vrt_Light_LightPng):
#     _icon = "laptop 1.png"
# class Laptop 3LightPng(_Vrt_Light_LightPng):
#     _icon = "laptop 3.png"
# class Large Hmi Panel 1LightPng(_Vrt_Light_LightPng):
#     _icon = "large hmi panel 1.png"
# class Laser Printer 1LightPng(_Vrt_Light_LightPng):
#     _icon = "laser printer 1.png"
# class Laser Printer 3LightPng(_Vrt_Light_LightPng):
#     _icon = "laser printer 3.png"
# class LeadAcid Battery 1LightPng(_Vrt_Light_LightPng):
#     _icon = "lead-acid battery 1.png"
# class Mail Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "mail server 1.png"
# class Microwave Satellite Base 1LightPng(_Vrt_Light_LightPng):
#     _icon = "microwave satellite base 1.png"
# class MultiRole Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "multi-role server 1.png"
# class Network Attached Storage 1LightPng(_Vrt_Light_LightPng):
#     _icon = "network attached storage 1.png"
# class Projector 1LightPng(_Vrt_Light_LightPng):
#     _icon = "projector 1.png"
# class Rack Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "rack server 1.png"
# class Rackmount Switch 1LightPng(_Vrt_Light_LightPng):
#     _icon = "rackmount switch 1.png"
# class Role Emblem  AuthenticationLightPng(_Vrt_Light_LightPng):
#     _icon = "role emblem - authentication.png"
# class Role Emblem  Data Acquisition LightPng(Scada)LightPng(_Vrt_Light_LightPng):
#     _icon = "role emblem - data acquisition LightPng(scada).png"
# class Role Emblem  DatabaseLightPng(_Vrt_Light_LightPng):
#     _icon = "role emblem - database.png"
# class Role Emblem  DirectoryLightPng(_Vrt_Light_LightPng):
#     _icon = "role emblem - directory.png"
# class Role Emblem  FileLightPng(_Vrt_Light_LightPng):
#     _icon = "role emblem - file.png"
# class Role Emblem  MailLightPng(_Vrt_Light_LightPng):
#     _icon = "role emblem - mail.png"
# class Role Emblem  VideoLightPng(_Vrt_Light_LightPng):
#     _icon = "role emblem - video.png"
# class Role Emblem  Virtualisation ObjectLightPng(_Vrt_Light_LightPng):
#     _icon = "role emblem - virtualisation object.png"
# class Role Emblem  VirtualisationLightPng(_Vrt_Light_LightPng):
#     _icon = "role emblem - virtualisation.png"
# class Role Emblem  WebLightPng(_Vrt_Light_LightPng):
#     _icon = "role emblem - web.png"
# class Router 1LightPng(_Vrt_Light_LightPng):
#     _icon = "router 1.png"
# class Router FirewallLightPng(_Vrt_Light_LightPng):
#     _icon = "router firewall.png"
# class RouterLightPng(_Vrt_Light_LightPng):
#     _icon = "router.png"
# class SinglePhase Energy Meter LightPng(Din)LightPng(_Vrt_Light_LightPng):
#     _icon = "single-phase energy meter LightPng(din).png"
# class SinglePhase Energy Meter 1LightPng(_Vrt_Light_LightPng):
#     _icon = "single-phase energy meter 1.png"
# class Small Hmi Panel 1LightPng(_Vrt_Light_LightPng):
#     _icon = "small hmi panel 1.png"
# class Small Touch Panel 1LightPng(_Vrt_Light_LightPng):
#     _icon = "small touch panel 1.png"
# class Smartphone 1LightPng(_Vrt_Light_LightPng):
#     _icon = "smartphone 1.png"
# class Smartphone 3LightPng(_Vrt_Light_LightPng):
#     _icon = "smartphone 3.png"
# class Solar Pv Panel 1LightPng(_Vrt_Light_LightPng):
#     _icon = "solar pv panel 1.png"
# class Solar Pv Panel 2LightPng(_Vrt_Light_LightPng):
#     _icon = "solar pv panel 2.png"
# class Switch 1LightPng(_Vrt_Light_LightPng):
#     _icon = "switch 1.png"
# class Switch 2LightPng(_Vrt_Light_LightPng):
#     _icon = "switch 2.png"
# class Tablet 1LightPng(_Vrt_Light_LightPng):
#     _icon = "tablet 1.png"
# class Tablet 3LightPng(_Vrt_Light_LightPng):
#     _icon = "tablet 3.png"
# class Telephone 1LightPng(_Vrt_Light_LightPng):
#     _icon = "telephone 1.png"
# class Telephone 3LightPng(_Vrt_Light_LightPng):
#     _icon = "telephone 3.png"
# class Thin Client 1LightPng(_Vrt_Light_LightPng):
#     _icon = "thin client 1.png"
# class Thin Client 3LightPng(_Vrt_Light_LightPng):
#     _icon = "thin client 3.png"
# class ThreePhase Energy Meter LightPng(Din)LightPng(_Vrt_Light_LightPng):
#     _icon = "three-phase energy meter LightPng(din).png"
# class ThreePhase Energy Meter 1LightPng(_Vrt_Light_LightPng):
#     _icon = "three-phase energy meter 1.png"
# class ThreePhase MultiFunction Meter 1LightPng(_Vrt_Light_LightPng):
#     _icon = "three-phase multi-function meter 1.png"
# class ThreePhase Power Quality Analyser 1LightPng(_Vrt_Light_LightPng):
#     _icon = "three-phase power quality analyser 1.png"
# class Tower Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "tower server 1.png"
# class Unified Communications Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "unified communications server 1.png"
# class Uninterruptible Power Supply LightPng(Ups) 1LightPng(_Vrt_Light_LightPng):
#     _icon = "uninterruptible power supply LightPng(ups) 1.png"
# class Video Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "video server 1.png"
# class Virtualisation Object Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "virtualisation object server 1.png"
# class Virtualisation Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "virtualisation server 1.png"
# class Vpn Concentrator 1LightPng(_Vrt_Light_LightPng):
#     _icon = "vpn concentrator 1.png"
# class Vpn Concentrator 2LightPng(_Vrt_Light_LightPng):
#     _icon = "vpn concentrator 2.png"
# class Wages Hub A Series 1LightPng(_Vrt_Light_LightPng):
#     _icon = "wages hub a series 1.png"
# class Water Thermal MeterLightPng(_Vrt_Light_LightPng):
#     _icon = "water thermal meter.png"
# class Web Server 1LightPng(_Vrt_Light_LightPng):
#     _icon = "web server 1.png"
# class Wired Segment LightPng(Internet)LightPng(_Vrt_Light_LightPng):
#     _icon = "wired segment LightPng(internet).png"
# class Wired Segment LightPng(Subnet)LightPng(_Vrt_Light_LightPng):
#     _icon = "wired segment LightPng(subnet).png"
# class Wireless Access Point 1LightPng(_Vrt_Light_LightPng):
#     _icon = "wireless access point 1.png"
# class Wireless Access Point 2LightPng(_Vrt_Light_LightPng):
#     _icon = "wireless access point 2.png"
# class Wireless Base 1LightPng(_Vrt_Light_LightPng):
#     _icon = "wireless base 1.png"
# class Wireless Router Access Point 1LightPng(_Vrt_Light_LightPng):
#     _icon = "wireless router access point 1.png"
# class Wireless Router Access Point 3LightPng(_Vrt_Light_LightPng):
#     _icon = "wireless router access point 3.png"
# class Wireless Router FirewallLightPng(_Vrt_Light_LightPng):
#     _icon = "wireless router firewall.png"
# class Wireless RouterLightPng(_Vrt_Light_LightPng):
#     _icon = "wireless router.png"
# class Workgroup Switch 1LightPng(_Vrt_Light_LightPng):
#     _icon = "workgroup switch 1.png"
#
# Aliases
