# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _ICONS


class _Vrt_Dark_DarkPng(_ICONS):
    _type = "VRT_dark_DarkPng"
    _icon_dir = "../resources/icons/VRT_Icons/VRT_DarkPng/VRT_dark_DarkPng"


class LaserScanner1DarkPng(_Vrt_Dark_DarkPng):
    _icon = "2dlaserscanner1.png"


class LaserScannerDarkPng(_Vrt_Dark_DarkPng):
    _icon = "2d laser scanner 2.png"


class LaserScanner5DarkPng(_Vrt_Dark_DarkPng):
    _icon = "3dlaserscanner1.png"


class LaserScanner4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "3d laser scanner 2.png"


class AegisDatacellCellularDataloggerDarkPng(_Vrt_Dark_DarkPng):
    _icon = "aegis datacell cellular datalogger 2.png"


class ApplianceDarkPng(_Vrt_Dark_DarkPng):
    _icon = "appliance 2.png"


class AtmSwitchDarkPng(_Vrt_Dark_DarkPng):
    _icon = "atm switch 1.png"


class AtmSwitch2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "atm switch 2.png"


class AuthenticationServer2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "authentication server 2.png"


class CctvCamera2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "cctv camera 2.png"


class CctvCamera4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "cctv camera 4.png"


class CommunicationsServerDarkPng(_Vrt_Dark_DarkPng):
    _icon = "communications server.png"


class CompactPlc2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "compact plc 2.png"


class DataAcquisitionScadaServer2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "data acquisition DarkPng(scada) server 2.png"


class DataLoggerRtu2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "data logger rtu 2.png"


class DatabaseServerDarkPng(_Vrt_Dark_DarkPng):
    _icon = "database server 2.png"


class DesktopDarkPng(_Vrt_Dark_DarkPng):
    _icon = "desktop 2.png"


class Desktop2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "desktop 4.png"


class DialUpModemDarkPng(_Vrt_Dark_DarkPng):
    _icon = "dial-up modem 2.png"


class DirectoryServerDarkPng(_Vrt_Dark_DarkPng):
    _icon = "directory server 2.png"


class DirectoryServer3DarkPng(_Vrt_Dark_DarkPng):
    _icon = "directory server.png"


class DocumentScanner2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "document scanner 2.png"


class DocumentScanner4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "document scanner 4.png"


class DocumentScanner6DarkPng(_Vrt_Dark_DarkPng):
    _icon = "document scanner 6.png"


class DocumentScanner8DarkPng(_Vrt_Dark_DarkPng):
    _icon = "document scanner 8.png"


class EndUsers2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "end users 2.png"


class Facsimile2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "facsimile 2.png"


class Facsimile4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "facsimile 4.png"


class FibreOpticBreakOutTray2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "FibreOpticBreak-outTray2.png"


class FileServer2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "file server 2.png"


class Firewall1DarkPng(_Vrt_Dark_DarkPng):
    _icon = "firewall 1.png"


class Firewall2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "firewall 2.png"


class FlatPanelDisplay2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "flat panel display 2.png"


class GenericBlackBox2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "generic black box 2.png"


class GenericPlcDcsController2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "generic plc dcs controller 2.png"


class Hub1DarkPng(_Vrt_Dark_DarkPng):
    _icon = "hub 1.png"


class Hub2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "hub 2.png"


class IndustrialBarcodeScanner2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "industrial barcode scanner 2.png"


class IndustrialBarcodeScanner4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "industrial barcode scanner 4.png"


class IndustrialCellularModem2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "industrial cellular modem 2.png"


class IndustrialCellularModem4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "industrial cellular modem 4.png"


class IndustrialEthernetToSerialConverter2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "industrial ethernet to serial converter 2.png"


class IndustrialFibreToEthernetConverter2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "industrial fibre to ethernet converter 2.png"


class IndustrialPc2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "industrial pc 2.png"


class IndustrialPc4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "industrial pc 4.png"


class IndustrialSwitch2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "industrial switch 2.png"


class InkjetPrinter2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "inkjet printer 2.png"


class InkjetPrinter4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "inkjet printer 4.png"


class Laptop2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "laptop 2.png"


class Laptop4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "laptop 4.png"


class LargeHmiPanel2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "large hmi panel 2.png"


class LaserPrinter2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "laser printer 2.png"


class LaserPrinter4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "laser printer 4.png"


class LeadAcidBattery2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "lead-acid battery 2.png"


class MailServer2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "mail server 2.png"


class MicrowaveSatelliteBase2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "microwave satellite base 2.png"


class MultiRoleServer2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "multi-role server 2.png"


class NetworkAttachedStorage2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "network attached storage 2.png"


class Projector2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "projector 2.png"


class RackServer2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "rack server 2.png"


class RackmountSwitch2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "rackmount switch 2.png"


class RoleEmblemAuthenticationDarkPng(_Vrt_Dark_DarkPng):
    _icon = "role emblem - authentication.png"


class RoleEmblemDataAcquisitionScadaDarkPng(_Vrt_Dark_DarkPng):
    _icon = "role emblem - data acquisition DarkPng(scada).png"


class RoleEmblemDatabaseDarkPng(_Vrt_Dark_DarkPng):
    _icon = "role emblem - database.png"


class RoleEmblemDirectoryDarkPng(_Vrt_Dark_DarkPng):
    _icon = "role emblem - directory.png"


class RoleEmblemFileDarkPng(_Vrt_Dark_DarkPng):
    _icon = "role emblem - file.png"


class RoleEmblemMailDarkPng(_Vrt_Dark_DarkPng):
    _icon = "role emblem - mail.png"


class RoleEmblemVideoDarkPng(_Vrt_Dark_DarkPng):
    _icon = "role emblem - video.png"


class RoleEmblemVirtualisationObjectDarkPng(_Vrt_Dark_DarkPng):
    _icon = "role emblem - virtualisation object.png"


class RoleEmblemVirtualisationDarkPng(_Vrt_Dark_DarkPng):
    _icon = "role emblem - virtualisation.png"


class RoleEmblemWebDarkPng(_Vrt_Dark_DarkPng):
    _icon = "role emblem - web.png"


class Router2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "router 2.png"


class RouterFirewallDarkPng(_Vrt_Dark_DarkPng):
    _icon = "router firewall.png"


class RouterDarkPng(_Vrt_Dark_DarkPng):
    _icon = "router.png"


class ServerRackOpenDarkPng(_Vrt_Dark_DarkPng):
    _icon = "server rack - open.png"


class ServerRackDarkPng(_Vrt_Dark_DarkPng):
    _icon = "server rack.png"


class SinglePhaseEnergyMeter2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "single-phase energy meter 2.png"


class SmallHmiPanel2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "small hmi panel 2.png"


class SmallTouchPanel2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "small touch panel 2.png"


class Smartphone2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "smartphone 2.png"


class Smartphone4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "smartphone 4.png"


class Switch1DarkPng(_Vrt_Dark_DarkPng):
    _icon = "switch 1.png"


class Switch2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "switch 2.png"


class Tablet2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "tablet 2.png"


class Tablet4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "tablet 4.png"


class Telephone2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "telephone 2.png"


class Telephone4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "telephone 4.png"


class ThinClient2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "thin client 2.png"


class ThinClient4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "thin client 4.png"


class ThreePhaseEnergyMeter2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "three-phase energy meter 2.png"


class ThreePhaseMultiFunctionMeter2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "three-phase multi-function meter 2.png"


class ThreePhasePowerQualityAnalyser2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "three-phase power quality analyser 2.png"


class TowerServer2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "tower server 2.png"


class UnifiedCommunicationsServer2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "unified communications server 2.png"


class UninterruptiblePowerSupplyUps2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "uninterruptible power supply DarkPng(ups) 2.png"


class UsbKeyDongle1DarkPng(_Vrt_Dark_DarkPng):
    _icon = "usb key dongle 1.png"


class UsbKeyDongle2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "usb key dongle 2.png"


class UsbKeyDongle3DarkPng(_Vrt_Dark_DarkPng):
    _icon = "usb key dongle 3.png"


class UsbKeyDongle4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "usb key dongle 4.png"


class UsbKeyDongle5DarkPng(_Vrt_Dark_DarkPng):
    _icon = "usb key dongle 5.png"


class UsbKeyDongle6DarkPng(_Vrt_Dark_DarkPng):
    _icon = "usb key dongle 6.png"


class UsbKeyDongle7DarkPng(_Vrt_Dark_DarkPng):
    _icon = "usb key dongle 7.png"


class UsbKeyDongle8DarkPng(_Vrt_Dark_DarkPng):
    _icon = "usb key dongle 8.png"


class VideoServer2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "video server 2.png"


class VideoWallCubeDarkPng(_Vrt_Dark_DarkPng):
    _icon = "video wall cube.png"


class VideoWallDarkPng(_Vrt_Dark_DarkPng):
    _icon = "video wall.png"


class VirtualisationObjectServer2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "virtualisation object server 2.png"


class VirtualisationServer2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "virtualisation server 2.png"


class VpnConcentrator1DarkPng(_Vrt_Dark_DarkPng):
    _icon = "vpn concentrator 1.png"


class VpnConcentrator2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "vpn concentrator 2.png"


class WagesHubASeries2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "wages hub a series 2.png"


class WebServer2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "web server 2.png"


class WiredSegmentInternetDarkPng(_Vrt_Dark_DarkPng):
    _icon = "wired segment DarkPng(internet).png"


class WiredSegmentSubnetDarkPng(_Vrt_Dark_DarkPng):
    _icon = "wired segment DarkPng(subnet).png"


class WirelessAccessPoint1DarkPng(_Vrt_Dark_DarkPng):
    _icon = "wireless access point 1.png"


class WirelessAccessPoint2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "wireless access point 2.png"


class WirelessBase2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "wireless base 2.png"


class WirelessRouterAccessPoint2DarkPng(_Vrt_Dark_DarkPng):
    _icon = "wireless router access point 2.png"


class WirelessRouterAccessPoint4DarkPng(_Vrt_Dark_DarkPng):
    _icon = "wireless router access point 4.png"


class WirelessRouterFirewallDarkPng(_Vrt_Dark_DarkPng):
    _icon = "wireless router firewall.png"


class WirelessRouterDarkPng(_Vrt_Dark_DarkPng):
    _icon = "wireless router.png"


class WorkgroupSwitch3DarkPng(_Vrt_Dark_DarkPng):
    _icon = "workgroup switch 2.png"

# Aliases
