# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _ICONS


class _Vrt_Light_SVG(_ICONS):
    _type = "VRT_Light_SVG"
    _icon_dir = "../resources/icons/VRT_Icons/VRT_svg/VRT_light_svg"


class LaserScanner1LLight(_Vrt_Light_SVG):
    _icon = "2dlaserscanner1.svg"


class LaserScannerLight(_Vrt_Light_SVG):
    _icon = "2d laser scanner 2.svg"


class LaserScanner5Light(_Vrt_Light_SVG):
    _icon = "3d laser scanner 1.svg"


class LaserScanner4Light(_Vrt_Light_SVG):
    _icon = "3d laser scanner 2.svg"


class AegisDatacellCellularDataloggerLight(_Vrt_Light_SVG):
    _icon = "aegis datacell cellular datalogger 2.svg"


class ApplianceLight(_Vrt_Light_SVG):
    _icon = "appliance 2.svg"


class AtmSwitchLight(_Vrt_Light_SVG):
    _icon = "atm switch 1.svg"


class AtmSwitch2Light(_Vrt_Light_SVG):
    _icon = "atm switch 2.svg"


class AuthenticationServer2Light(_Vrt_Light_SVG):
    _icon = "authentication server 2.svg"


class CctvCamera2Light(_Vrt_Light_SVG):
    _icon = "cctv camera 2.svg"


class CctvCamera4Light(_Vrt_Light_SVG):
    _icon = "cctv camera 4.svg"


class CommunicationsServerLight(_Vrt_Light_SVG):
    _icon = "communications server.svg"


class CompactPlc2Light(_Vrt_Light_SVG):
    _icon = "compact plc 2.svg"


class DataAcquisitionScadaServer2Light(_Vrt_Light_SVG):
    _icon = "data acquisition Light(scada) server 2.svg"


class DataLoggerRtu2Light(_Vrt_Light_SVG):
    _icon = "data logger rtu 2.svg"


class DatabaseServerLight(_Vrt_Light_SVG):
    _icon = "database server 2.svg"


class DesktopLight(_Vrt_Light_SVG):
    _icon = "desktop 2.svg"


class Desktop2Light(_Vrt_Light_SVG):
    _icon = "desktop 4.svg"


class DialUpModemLight(_Vrt_Light_SVG):
    _icon = "dial-up modem 2.svg"


class DirectoryServerLight(_Vrt_Light_SVG):
    _icon = "directory server 2.svg"


class DirectoryServer3Light(_Vrt_Light_SVG):
    _icon = "directory server.svg"


class DocumentScanner2Light(_Vrt_Light_SVG):
    _icon = "document scanner 2.svg"


class DocumentScanner4Light(_Vrt_Light_SVG):
    _icon = "document scanner 4.svg"


class DocumentScanner6Light(_Vrt_Light_SVG):
    _icon = "document scanner 6.svg"


class DocumentScanner8Light(_Vrt_Light_SVG):
    _icon = "document scanner 8.svg"


class EndUsers2Light(_Vrt_Light_SVG):
    _icon = "end users 2.svg"


class Facsimile2Light(_Vrt_Light_SVG):
    _icon = "facsimile 2.svg"


class Facsimile4Light(_Vrt_Light_SVG):
    _icon = "facsimile 4.svg"


class FibreOpticBreakOutTray2Light(_Vrt_Light_SVG):
    _icon = "FibreOpticBreak-outTray2.svg"


class FileServer2Light(_Vrt_Light_SVG):
    _icon = "file server 2.svg"


class Firewall1Light(_Vrt_Light_SVG):
    _icon = "firewall 1.svg"


class Firewall2Light(_Vrt_Light_SVG):
    _icon = "firewall 2.svg"


class FlatPanelDisplay2Light(_Vrt_Light_SVG):
    _icon = "flat panel display 2.svg"


class GenericBlackBox2Light(_Vrt_Light_SVG):
    _icon = "generic black box 2.svg"


class GenericPlcDcsController2Light(_Vrt_Light_SVG):
    _icon = "generic plc dcs controller 2.svg"


class Hub1Light(_Vrt_Light_SVG):
    _icon = "hub 1.svg"


class Hub2Light(_Vrt_Light_SVG):
    _icon = "hub 2.svg"


class IndustrialBarcodeScanner2Light(_Vrt_Light_SVG):
    _icon = "industrial barcode scanner 2.svg"


class IndustrialBarcodeScanner4Light(_Vrt_Light_SVG):
    _icon = "industrial barcode scanner 4.svg"


class IndustrialCellularModem2Light(_Vrt_Light_SVG):
    _icon = "industrial cellular modem 2.svg"


class IndustrialCellularModem4Light(_Vrt_Light_SVG):
    _icon = "industrial cellular modem 4.svg"


class IndustrialEthernetToSerialConverter2Light(_Vrt_Light_SVG):
    _icon = "industrial ethernet to serial converter 2.svg"


class IndustrialFibreToEthernetConverter2Light(_Vrt_Light_SVG):
    _icon = "industrial fibre to ethernet converter 2.svg"


class IndustrialPc2Light(_Vrt_Light_SVG):
    _icon = "industrial pc 2.svg"


class IndustrialPc4Light(_Vrt_Light_SVG):
    _icon = "industrial pc 4.svg"


class IndustrialSwitch2Light(_Vrt_Light_SVG):
    _icon = "industrial switch 2.svg"


class InkjetPrinter2Light(_Vrt_Light_SVG):
    _icon = "inkjet printer 2.svg"


class InkjetPrinter4Light(_Vrt_Light_SVG):
    _icon = "inkjet printer 4.svg"


class Laptop2Light(_Vrt_Light_SVG):
    _icon = "laptop 2.svg"


class Laptop4Light(_Vrt_Light_SVG):
    _icon = "laptop 4.svg"


class LargeHmiPanel2Light(_Vrt_Light_SVG):
    _icon = "large hmi panel 2.svg"


class LaserPrinter2Light(_Vrt_Light_SVG):
    _icon = "laser printer 2.svg"


class LaserPrinter4Light(_Vrt_Light_SVG):
    _icon = "laser printer 4.svg"


class LeadAcidBattery2Light(_Vrt_Light_SVG):
    _icon = "lead-acid battery 2.svg"


class MailServer2Light(_Vrt_Light_SVG):
    _icon = "mail server 2.svg"


class MicrowaveSatelliteBase2Light(_Vrt_Light_SVG):
    _icon = "microwave satellite base 2.svg"


class MultiRoleServer2Light(_Vrt_Light_SVG):
    _icon = "multi-role server 2.svg"


class NetworkAttachedStorage2Light(_Vrt_Light_SVG):
    _icon = "network attached storage 2.svg"


class Projector2Light(_Vrt_Light_SVG):
    _icon = "projector 2.svg"


class RackServer2Light(_Vrt_Light_SVG):
    _icon = "rack server 2.svg"


class RackmountSwitch2Light(_Vrt_Light_SVG):
    _icon = "rackmount switch 2.svg"


class RoleEmblemAuthenticationLight(_Vrt_Light_SVG):
    _icon = "role emblem - authentication.svg"


class RoleEmblemDataAcquisitionScadaLight(_Vrt_Light_SVG):
    _icon = "role emblem - data acquisition Light(scada).svg"


class RoleEmblemDatabaseLight(_Vrt_Light_SVG):
    _icon = "role emblem - database.svg"


class RoleEmblemDirectoryLight(_Vrt_Light_SVG):
    _icon = "role emblem - directory.svg"


class RoleEmblemFileLight(_Vrt_Light_SVG):
    _icon = "role emblem - file.svg"


class RoleEmblemMailLight(_Vrt_Light_SVG):
    _icon = "role emblem - mail.svg"


class RoleEmblemVideoLight(_Vrt_Light_SVG):
    _icon = "role emblem - video.svg"


class RoleEmblemVirtualisationObjectLight(_Vrt_Light_SVG):
    _icon = "role emblem - virtualisation object.svg"


class RoleEmblemVirtualisationLight(_Vrt_Light_SVG):
    _icon = "role emblem - virtualisation.svg"


class RoleEmblemWebLight(_Vrt_Light_SVG):
    _icon = "role emblem - web.svg"


class Router2Light(_Vrt_Light_SVG):
    _icon = "router 2.svg"


class RouterFirewallLight(_Vrt_Light_SVG):
    _icon = "router firewall.svg"


class RouterLight(_Vrt_Light_SVG):
    _icon = "router.svg"


class ServerRackOpenLight(_Vrt_Light_SVG):
    _icon = "server rack - open.svg"


class ServerRackLight(_Vrt_Light_SVG):
    _icon = "server rack.svg"


class SinglePhaseEnergyMeter2Light(_Vrt_Light_SVG):
    _icon = "single-phase energy meter 2.svg"


class SmallHmiPanel2Light(_Vrt_Light_SVG):
    _icon = "small hmi panel 2.svg"


class SmallTouchPanel2Light(_Vrt_Light_SVG):
    _icon = "small touch panel 2.svg"


class Smartphone2Light(_Vrt_Light_SVG):
    _icon = "smartphone 2.svg"


class Smartphone4Light(_Vrt_Light_SVG):
    _icon = "smartphone 4.svg"


class Switch1Light(_Vrt_Light_SVG):
    _icon = "switch 1.svg"


class Switch2Light(_Vrt_Light_SVG):
    _icon = "switch 2.svg"


class Tablet2Light(_Vrt_Light_SVG):
    _icon = "tablet 2.svg"


class Tablet4Light(_Vrt_Light_SVG):
    _icon = "tablet 4.svg"


class Telephone2Light(_Vrt_Light_SVG):
    _icon = "telephone 2.svg"


class Telephone4Light(_Vrt_Light_SVG):
    _icon = "telephone 4.svg"


class ThinClient2Light(_Vrt_Light_SVG):
    _icon = "thin client 2.svg"


class ThinClient4Light(_Vrt_Light_SVG):
    _icon = "thin client 4.svg"


class ThreePhaseEnergyMeter2Light(_Vrt_Light_SVG):
    _icon = "three-phase energy meter 2.svg"


class ThreePhaseMultiFunctionMeter2Light(_Vrt_Light_SVG):
    _icon = "three-phase multi-function meter 2.svg"


class ThreePhasePowerQualityAnalyser2Light(_Vrt_Light_SVG):
    _icon = "three-phase power quality analyser 2.svg"


class TowerServer2Light(_Vrt_Light_SVG):
    _icon = "tower server 2.svg"


class UnifiedCommunicationsServer2Light(_Vrt_Light_SVG):
    _icon = "unified communications server 2.svg"


class UninterruptiblePowerSupplyUps2Light(_Vrt_Light_SVG):
    _icon = "uninterruptible power supply Light(ups) 2.svg"


class UsbKeyDongle1Light(_Vrt_Light_SVG):
    _icon = "usb key dongle 1.svg"


class UsbKeyDongle2Light(_Vrt_Light_SVG):
    _icon = "usb key dongle 2.svg"


class UsbKeyDongle3Light(_Vrt_Light_SVG):
    _icon = "usb key dongle 3.svg"


class UsbKeyDongle4Light(_Vrt_Light_SVG):
    _icon = "usb key dongle 4.svg"


class UsbKeyDongle5Light(_Vrt_Light_SVG):
    _icon = "usb key dongle 5.svg"


class UsbKeyDongle6Light(_Vrt_Light_SVG):
    _icon = "usb key dongle 6.svg"


class UsbKeyDongle7Light(_Vrt_Light_SVG):
    _icon = "usb key dongle 7.svg"


class UsbKeyDongle8Light(_Vrt_Light_SVG):
    _icon = "usb key dongle 8.svg"


class VideoServer2Light(_Vrt_Light_SVG):
    _icon = "video server 2.svg"


class VideoWallCubeLight(_Vrt_Light_SVG):
    _icon = "video wall cube.svg"


class VideoWallLight(_Vrt_Light_SVG):
    _icon = "video wall.svg"


class VirtualisationObjectServer2Light(_Vrt_Light_SVG):
    _icon = "virtualisation object server 2.svg"


class VirtualisationServer2Light(_Vrt_Light_SVG):
    _icon = "virtualisation server 2.svg"


class VpnConcentrator1Light(_Vrt_Light_SVG):
    _icon = "vpn concentrator 1.svg"


class VpnConcentrator2Light(_Vrt_Light_SVG):
    _icon = "vpn concentrator 2.svg"


class WagesHubASeries2Light(_Vrt_Light_SVG):
    _icon = "wages hub a series 2.svg"


class WebServer2Light(_Vrt_Light_SVG):
    _icon = "web server 2.svg"


class WiredSegmentInternetLight(_Vrt_Light_SVG):
    _icon = "wired segment Light(internet).svg"


class WiredSegmentSubnetLight(_Vrt_Light_SVG):
    _icon = "wired segment Light(subnet).svg"


class WirelessAccessPoint1Light(_Vrt_Light_SVG):
    _icon = "wireless access point 1.svg"


class WirelessAccessPoint2Light(_Vrt_Light_SVG):
    _icon = "wireless access point 2.svg"


class WirelessBase2Light(_Vrt_Light_SVG):
    _icon = "wireless base 2.svg"


class WirelessRouterAccessPoint2Light(_Vrt_Light_SVG):
    _icon = "wireless router access point 2.svg"


class WirelessRouterAccessPoint4Light(_Vrt_Light_SVG):
    _icon = "wireless router access point 4.svg"


class WirelessRouterFirewallLight(_Vrt_Light_SVG):
    _icon = "wireless router firewall.svg"


class WirelessRouterLight(_Vrt_Light_SVG):
    _icon = "wireless router.svg"


class WorkgroupSwitch3Light(_Vrt_Light_SVG):
    _icon = "workgroup switch 2.svg"

# Aliases
