# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _ICONS


class _Vrt_Dark_SVG(_ICONS):
    _type = "VRT_dark_SVG"
    _icon_dir = "../resources/icons/VRT_Icons/VRT_svg/VRT_dark_svg"


class LaserScanner1Dark(_Vrt_Dark_SVG):
    _icon = "2dlaserscanner1.svg"


class LaserScannerDark(_Vrt_Dark_SVG):
    _icon = "2d laser scanner 2.svg"


class LaserScanner5Dark(_Vrt_Dark_SVG):
    _icon = "3d laser scanner 1.svg"


class LaserScanner4Dark(_Vrt_Dark_SVG):
    _icon = "3d laser scanner 2.svg"


class AegisDatacellCellularDataloggerDark(_Vrt_Dark_SVG):
    _icon = "aegis datacell cellular datalogger 2.svg"


class ApplianceDark(_Vrt_Dark_SVG):
    _icon = "appliance 2.svg"


class AtmSwitchDark(_Vrt_Dark_SVG):
    _icon = "atm switch 1.svg"


class AtmSwitch2Dark(_Vrt_Dark_SVG):
    _icon = "atm switch 2.svg"


class AuthenticationServer2Dark(_Vrt_Dark_SVG):
    _icon = "authentication server 2.svg"


class CctvCamera2Dark(_Vrt_Dark_SVG):
    _icon = "cctv camera 2.svg"


class CctvCamera4Dark(_Vrt_Dark_SVG):
    _icon = "cctv camera 4.svg"


class CommunicationsServerDark(_Vrt_Dark_SVG):
    _icon = "communications server.svg"


class CompactPlc2Dark(_Vrt_Dark_SVG):
    _icon = "compact plc 2.svg"


class DataAcquisitionScadaServer2Dark(_Vrt_Dark_SVG):
    _icon = "data acquisition Dark(scada) server 2.svg"


class DataLoggerRtu2Dark(_Vrt_Dark_SVG):
    _icon = "data logger rtu 2.svg"


class DatabaseServerDark(_Vrt_Dark_SVG):
    _icon = "database server 2.svg"


class DesktopDark(_Vrt_Dark_SVG):
    _icon = "desktop 2.svg"


class Desktop2Dark(_Vrt_Dark_SVG):
    _icon = "desktop 4.svg"


class DialUpModemDark(_Vrt_Dark_SVG):
    _icon = "dial-up modem 2.svg"


class DirectoryServerDark(_Vrt_Dark_SVG):
    _icon = "directory server 2.svg"


class DirectoryServer3Dark(_Vrt_Dark_SVG):
    _icon = "directory server.svg"


class DocumentScanner2Dark(_Vrt_Dark_SVG):
    _icon = "document scanner 2.svg"


class DocumentScanner4Dark(_Vrt_Dark_SVG):
    _icon = "document scanner 4.svg"


class DocumentScanner6Dark(_Vrt_Dark_SVG):
    _icon = "document scanner 6.svg"


class DocumentScanner8Dark(_Vrt_Dark_SVG):
    _icon = "document scanner 8.svg"


class EndUsers2Dark(_Vrt_Dark_SVG):
    _icon = "end users 2.svg"


class Facsimile2Dark(_Vrt_Dark_SVG):
    _icon = "facsimile 2.svg"


class Facsimile4Dark(_Vrt_Dark_SVG):
    _icon = "facsimile 4.svg"


class FibreOpticBreakOutTray2Dark(_Vrt_Dark_SVG):
    _icon = "FibreOpticBreak-outTray2.svg"


class FileServer2Dark(_Vrt_Dark_SVG):
    _icon = "file server 2.svg"


class Firewall1Dark(_Vrt_Dark_SVG):
    _icon = "firewall 1.svg"


class Firewall2Dark(_Vrt_Dark_SVG):
    _icon = "firewall 2.svg"


class FlatPanelDisplay2Dark(_Vrt_Dark_SVG):
    _icon = "flat panel display 2.svg"


class GenericBlackBox2Dark(_Vrt_Dark_SVG):
    _icon = "generic black box 2.svg"


class GenericPlcDcsController2Dark(_Vrt_Dark_SVG):
    _icon = "generic plc dcs controller 2.svg"


class Hub1Dark(_Vrt_Dark_SVG):
    _icon = "hub 1.svg"


class Hub2Dark(_Vrt_Dark_SVG):
    _icon = "hub 2.svg"


class IndustrialBarcodeScanner2Dark(_Vrt_Dark_SVG):
    _icon = "industrial barcode scanner 2.svg"


class IndustrialBarcodeScanner4Dark(_Vrt_Dark_SVG):
    _icon = "industrial barcode scanner 4.svg"


class IndustrialCellularModem2Dark(_Vrt_Dark_SVG):
    _icon = "industrial cellular modem 2.svg"


class IndustrialCellularModem4Dark(_Vrt_Dark_SVG):
    _icon = "industrial cellular modem 4.svg"


class IndustrialEthernetToSerialConverter2Dark(_Vrt_Dark_SVG):
    _icon = "industrial ethernet to serial converter 2.svg"


class IndustrialFibreToEthernetConverter2Dark(_Vrt_Dark_SVG):
    _icon = "industrial fibre to ethernet converter 2.svg"


class IndustrialPc2Dark(_Vrt_Dark_SVG):
    _icon = "industrial pc 2.svg"


class IndustrialPc4Dark(_Vrt_Dark_SVG):
    _icon = "industrial pc 4.svg"


class IndustrialSwitch2Dark(_Vrt_Dark_SVG):
    _icon = "industrial switch 2.svg"


class InkjetPrinter2Dark(_Vrt_Dark_SVG):
    _icon = "inkjet printer 2.svg"


class InkjetPrinter4Dark(_Vrt_Dark_SVG):
    _icon = "inkjet printer 4.svg"


class Laptop2Dark(_Vrt_Dark_SVG):
    _icon = "laptop 2.svg"


class Laptop4Dark(_Vrt_Dark_SVG):
    _icon = "laptop 4.svg"


class LargeHmiPanel2Dark(_Vrt_Dark_SVG):
    _icon = "large hmi panel 2.svg"


class LaserPrinter2Dark(_Vrt_Dark_SVG):
    _icon = "laser printer 2.svg"


class LaserPrinter4Dark(_Vrt_Dark_SVG):
    _icon = "laser printer 4.svg"


class LeadAcidBattery2Dark(_Vrt_Dark_SVG):
    _icon = "lead-acid battery 2.svg"


class MailServer2Dark(_Vrt_Dark_SVG):
    _icon = "mail server 2.svg"


class MicrowaveSatelliteBase2Dark(_Vrt_Dark_SVG):
    _icon = "microwave satellite base 2.svg"


class MultiRoleServer2Dark(_Vrt_Dark_SVG):
    _icon = "multi-role server 2.svg"


class NetworkAttachedStorage2Dark(_Vrt_Dark_SVG):
    _icon = "network attached storage 2.svg"


class Projector2Dark(_Vrt_Dark_SVG):
    _icon = "projector 2.svg"


class RackServer2Dark(_Vrt_Dark_SVG):
    _icon = "rack server 2.svg"


class RackmountSwitch2Dark(_Vrt_Dark_SVG):
    _icon = "rackmount switch 2.svg"


class RoleEmblemAuthenticationDark(_Vrt_Dark_SVG):
    _icon = "role emblem - authentication.svg"


class RoleEmblemDataAcquisitionScadaDark(_Vrt_Dark_SVG):
    _icon = "role emblem - data acquisition Dark(scada).svg"


class RoleEmblemDatabaseDark(_Vrt_Dark_SVG):
    _icon = "role emblem - database.svg"


class RoleEmblemDirectoryDark(_Vrt_Dark_SVG):
    _icon = "role emblem - directory.svg"


class RoleEmblemFileDark(_Vrt_Dark_SVG):
    _icon = "role emblem - file.svg"


class RoleEmblemMailDark(_Vrt_Dark_SVG):
    _icon = "role emblem - mail.svg"


class RoleEmblemVideoDark(_Vrt_Dark_SVG):
    _icon = "role emblem - video.svg"


class RoleEmblemVirtualisationObjectDark(_Vrt_Dark_SVG):
    _icon = "role emblem - virtualisation object.svg"


class RoleEmblemVirtualisationDark(_Vrt_Dark_SVG):
    _icon = "role emblem - virtualisation.svg"


class RoleEmblemWebDark(_Vrt_Dark_SVG):
    _icon = "role emblem - web.svg"


class Router2Dark(_Vrt_Dark_SVG):
    _icon = "router 2.svg"


class RouterFirewallDark(_Vrt_Dark_SVG):
    _icon = "router firewall.svg"


class RouterDark(_Vrt_Dark_SVG):
    _icon = "router.svg"


class ServerRackOpenDark(_Vrt_Dark_SVG):
    _icon = "server rack - open.svg"


class ServerRackDark(_Vrt_Dark_SVG):
    _icon = "server rack.svg"


class SinglePhaseEnergyMeter2Dark(_Vrt_Dark_SVG):
    _icon = "single-phase energy meter 2.svg"


class SmallHmiPanel2Dark(_Vrt_Dark_SVG):
    _icon = "small hmi panel 2.svg"


class SmallTouchPanel2Dark(_Vrt_Dark_SVG):
    _icon = "small touch panel 2.svg"


class Smartphone2Dark(_Vrt_Dark_SVG):
    _icon = "smartphone 2.svg"


class Smartphone4Dark(_Vrt_Dark_SVG):
    _icon = "smartphone 4.svg"


class Switch1Dark(_Vrt_Dark_SVG):
    _icon = "switch 1.svg"


class Switch2Dark(_Vrt_Dark_SVG):
    _icon = "switch 2.svg"


class Tablet2Dark(_Vrt_Dark_SVG):
    _icon = "tablet 2.svg"


class Tablet4Dark(_Vrt_Dark_SVG):
    _icon = "tablet 4.svg"


class Telephone2Dark(_Vrt_Dark_SVG):
    _icon = "telephone 2.svg"


class Telephone4Dark(_Vrt_Dark_SVG):
    _icon = "telephone 4.svg"


class ThinClient2Dark(_Vrt_Dark_SVG):
    _icon = "thin client 2.svg"


class ThinClient4Dark(_Vrt_Dark_SVG):
    _icon = "thin client 4.svg"


class ThreePhaseEnergyMeter2Dark(_Vrt_Dark_SVG):
    _icon = "three-phase energy meter 2.svg"


class ThreePhaseMultiFunctionMeter2Dark(_Vrt_Dark_SVG):
    _icon = "three-phase multi-function meter 2.svg"


class ThreePhasePowerQualityAnalyser2Dark(_Vrt_Dark_SVG):
    _icon = "three-phase power quality analyser 2.svg"


class TowerServer2Dark(_Vrt_Dark_SVG):
    _icon = "tower server 2.svg"


class UnifiedCommunicationsServer2Dark(_Vrt_Dark_SVG):
    _icon = "unified communications server 2.svg"


class UninterruptiblePowerSupplyUps2Dark(_Vrt_Dark_SVG):
    _icon = "uninterruptible power supply Dark(ups) 2.svg"


class UsbKeyDongle1Dark(_Vrt_Dark_SVG):
    _icon = "usb key dongle 1.svg"


class UsbKeyDongle2Dark(_Vrt_Dark_SVG):
    _icon = "usb key dongle 2.svg"


class UsbKeyDongle3Dark(_Vrt_Dark_SVG):
    _icon = "usb key dongle 3.svg"


class UsbKeyDongle4Dark(_Vrt_Dark_SVG):
    _icon = "usb key dongle 4.svg"


class UsbKeyDongle5Dark(_Vrt_Dark_SVG):
    _icon = "usb key dongle 5.svg"


class UsbKeyDongle6Dark(_Vrt_Dark_SVG):
    _icon = "usb key dongle 6.svg"


class UsbKeyDongle7Dark(_Vrt_Dark_SVG):
    _icon = "usb key dongle 7.svg"


class UsbKeyDongle8Dark(_Vrt_Dark_SVG):
    _icon = "usb key dongle 8.svg"


class VideoServer2Dark(_Vrt_Dark_SVG):
    _icon = "video server 2.svg"


class VideoWallCubeDark(_Vrt_Dark_SVG):
    _icon = "video wall cube.svg"


class VideoWallDark(_Vrt_Dark_SVG):
    _icon = "video wall.svg"


class VirtualisationObjectServer2Dark(_Vrt_Dark_SVG):
    _icon = "virtualisation object server 2.svg"


class VirtualisationServer2Dark(_Vrt_Dark_SVG):
    _icon = "virtualisation server 2.svg"


class VpnConcentrator1Dark(_Vrt_Dark_SVG):
    _icon = "vpn concentrator 1.svg"


class VpnConcentrator2Dark(_Vrt_Dark_SVG):
    _icon = "vpn concentrator 2.svg"


class WagesHubASeries2Dark(_Vrt_Dark_SVG):
    _icon = "wages hub a series 2.svg"


class WebServer2Dark(_Vrt_Dark_SVG):
    _icon = "web server 2.svg"


class WiredSegmentInternetDark(_Vrt_Dark_SVG):
    _icon = "wired segment Dark(internet).svg"


class WiredSegmentSubnetDark(_Vrt_Dark_SVG):
    _icon = "wired segment Dark(subnet).svg"


class WirelessAccessPoint1Dark(_Vrt_Dark_SVG):
    _icon = "wireless access point 1.svg"


class WirelessAccessPoint2Dark(_Vrt_Dark_SVG):
    _icon = "wireless access point 2.svg"


class WirelessBase2Dark(_Vrt_Dark_SVG):
    _icon = "wireless base 2.svg"


class WirelessRouterAccessPoint2Dark(_Vrt_Dark_SVG):
    _icon = "wireless router access point 2.svg"


class WirelessRouterAccessPoint4Dark(_Vrt_Dark_SVG):
    _icon = "wireless router access point 4.svg"


class WirelessRouterFirewallDark(_Vrt_Dark_SVG):
    _icon = "wireless router firewall.svg"


class WirelessRouterDark(_Vrt_Dark_SVG):
    _icon = "wireless router.svg"


class WorkgroupSwitch3Dark(_Vrt_Dark_SVG):
    _icon = "workgroup switch 2.svg"

# Aliases
