# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _ICONS


class _Opensecur(_ICONS):
    _type = "opensecur"
    _icon_dir = "resources/icons/opensecur"


class OsaArrowGreenLeft(_Opensecur):
    _icon = "osa-arrow-green-left.png"


class OsaArrowYellowRight(_Opensecur):
    _icon = "osa-arrow-yellow-right.png"


class OsaAwareness(_Opensecur):
    _icon = "osa-awareness.png"


class OsaCameraWeb(_Opensecur):
    _icon = "osa-camera-web.png"


class OsaCloud(_Opensecur):
    _icon = "osa-cloud.png"


class OsaContract(_Opensecur):
    _icon = "osa-contract.png"


class OsaDatabase(_Opensecur):
    _icon = "osa-database.png"


class OsaDesktopImac(_Opensecur):
    _icon = "osa-desktop-imac.png"


class OsaDesktop(_Opensecur):
    _icon = "osa-desktop.png"


class OsaDeviceMusic(_Opensecur):
    _icon = "osa-device-music.png"


class OsaDeviceScanner(_Opensecur):
    _icon = "osa-device-scanner.png"


class OsaDeviceUsbWifi(_Opensecur):
    _icon = "osa-device-usb-wifi.png"


class OsaDeviceUsb(_Opensecur):
    _icon = "osa-device-usb.png"


class OsaDeviceWirelessRouter(_Opensecur):
    _icon = "osa-device-wireless-router.png"


class OsaDisposal(_Opensecur):
    _icon = "osa-disposal.png"


class OsaDriveHarddisk(_Opensecur):
    _icon = "osa-drive-harddisk.png"


class OsaDriveOptical(_Opensecur):
    _icon = "osa-drive-optical.png"


class OsaFirewall(_Opensecur):
    _icon = "osa-firewall.png"


class OsaHome(_Opensecur):
    _icon = "osa-home.png"


class OsaHub(_Opensecur):
    _icon = "osa-hub.png"


class OsaIcsDrive(_Opensecur):
    _icon = "osa-ics-drive.png"


class OsaIcsPlc(_Opensecur):
    _icon = "osa-ics-plc.png"


class OsaIcsThermometer(_Opensecur):
    _icon = "osa-ics-thermometer.png"


class OsaIdCard(_Opensecur):
    _icon = "osa-id-card.png"


class OsaImageGeneric(_Opensecur):
    _icon = "osa-image-generic.png"


class OsaIphone(_Opensecur):
    _icon = "osa-iphone.png"


class OsaLaptop(_Opensecur):
    _icon = "osa-laptop.png"


class OsaLifecycle(_Opensecur):
    _icon = "osa-lifecycle.png"


class OsaLightning(_Opensecur):
    _icon = "osa-lightning.png"


class OsaMediaFlash(_Opensecur):
    _icon = "osa-media-flash.png"


class OsaMediaOptical(_Opensecur):
    _icon = "osa-media-optical.png"


class OsaMediaTape(_Opensecur):
    _icon = "osa-media-tape.png"


class OsaMobilePda(_Opensecur):
    _icon = "osa-mobile-pda.png"


class OsaPadlock(_Opensecur):
    _icon = "osa-padlock.png"


class OsaPrinter(_Opensecur):
    _icon = "osa-printer.png"


class OsaServerApplication(_Opensecur):
    _icon = "osa-server-application.png"


class OsaServerDatabase(_Opensecur):
    _icon = "osa-server-database.png"


class OsaServerDirectory(_Opensecur):
    _icon = "osa-server-directory.png"


class OsaServerDistribution(_Opensecur):
    _icon = "osa-server-distribution.png"


class OsaServerFile(_Opensecur):
    _icon = "osa-server-file.png"


class OsaServerGateway(_Opensecur):
    _icon = "osa-server-gateway.png"


class OsaServerIdentity(_Opensecur):
    _icon = "osa-server-identity.png"


class OsaServerMail(_Opensecur):
    _icon = "osa-server-mail.png"


class OsaServerMedia(_Opensecur):
    _icon = "osa-server-media.png"


class OsaServerMonitor(_Opensecur):
    _icon = "osa-server-monitor.png"


class OsaServerProxy(_Opensecur):
    _icon = "osa-server-proxy.png"


class OsaServerTerminal(_Opensecur):
    _icon = "osa-server-terminal.png"


class OsaServerWeb(_Opensecur):
    _icon = "osa-server-web.png"


class OsaServer(_Opensecur):
    _icon = "osa-server.png"


class OsaSiteBranch(_Opensecur):
    _icon = "osa-site-branch.png"


class OsaSiteFactory(_Opensecur):
    _icon = "osa-site-factory.png"


class OsaSiteHeadOffice(_Opensecur):
    _icon = "osa-site-head-office.png"


class OsaSiteNeighbourhood(_Opensecur):
    _icon = "osa-site-neighbourhood.png"


class OsaUserAudit(_Opensecur):
    _icon = "osa-user-audit.png"


class OsaUserBlackHat(_Opensecur):
    _icon = "osa-user-black-hat.png"


class OsaUserBlueSecuritySpecialist(_Opensecur):
    _icon = "osa-user-blue-security-specialist.png"


class OsaUserBlueSysadmin(_Opensecur):
    _icon = "osa-user-blue-sysadmin.png"


class OsaUserBlueTester(_Opensecur):
    _icon = "osa-user-blue-tester.png"


class OsaUserBlueTie(_Opensecur):
    _icon = "osa-user-blue-tie.png"


class OsaUserBlue(_Opensecur):
    _icon = "osa-user-blue.png"


class OsaUserGreenArchitect(_Opensecur):
    _icon = "osa-user-green-architect.png"


class OsaUserGreenBusinessManager(_Opensecur):
    _icon = "osa-user-green-business-manager.png"


class OsaUserGreenDeveloper(_Opensecur):
    _icon = "osa-user-green-developer.png"


class OsaUserGreenOperations(_Opensecur):
    _icon = "osa-user-green-operations.png"


class OsaUserGreenProjectManager(_Opensecur):
    _icon = "osa-user-green-project-manager.png"


class OsaUserGreenServiceManager(_Opensecur):
    _icon = "osa-user-green-service-manager.png"


class OsaUserGreenWarning(_Opensecur):
    _icon = "osa-user-green-warning.png"


class OsaUserGreen(_Opensecur):
    _icon = "osa-user-green.png"


class OsaUserLargeGroup(_Opensecur):
    _icon = "osa-user-large-group.png"


class OsaUserWhiteHat(_Opensecur):
    _icon = "osa-user-white-hat.png"


class OsaUsersBlueGreen(_Opensecur):
    _icon = "osa-users-blue-green.png"


class OsaVPN(_Opensecur):
    _icon = "osa-vpn.png"


class OsaWarning(_Opensecur):
    _icon = "osa-warning.png"


class OsaWirelessNetwork(_Opensecur):
    _icon = "osa-wireless-network.png"


# Aliases
