# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _ICONS


class _OSA(_ICONS):
    _type = "osa"
    _icon_dir = "resources/icons/osa"


class OsaArrowGreenLeft(_OSA):
    _icon = "osa-arrow-green-left.png"


class OsaArrowYellowRight(_OSA):
    _icon = "osa-arrow-yellow-right.png"


class OsaAwareness(_OSA):
    _icon = "osa-awareness.png"


class OsaCameraWeb(_OSA):
    _icon = "osa-camera-web.png"


class OsaCloud(_OSA):
    _icon = "osa-cloud.png"


class OsaContract(_OSA):
    _icon = "osa-contract.png"


class OsaDatabase(_OSA):
    _icon = "osa-database.png"


class OsaDesktopImac(_OSA):
    _icon = "osa-desktop-imac.png"


class OsaDesktop(_OSA):
    _icon = "osa-desktop.png"


class OsaDeviceMusic(_OSA):
    _icon = "osa-device-music.png"


class OsaDeviceScanner(_OSA):
    _icon = "osa-device-scanner.png"


class OsaDeviceUsbWifi(_OSA):
    _icon = "osa-device-usb-wifi.png"


class OsaDeviceUsb(_OSA):
    _icon = "osa-device-usb.png"


class OsaDeviceWirelessRouter(_OSA):
    _icon = "osa-device-wireless-router.png"


class OsaDisposal(_OSA):
    _icon = "osa-disposal.png"


class OsaDriveHarddisk(_OSA):
    _icon = "osa-drive-harddisk.png"


class OsaDriveOptical(_OSA):
    _icon = "osa-drive-optical.png"


class OsaFirewall(_OSA):
    _icon = "osa-firewall.png"


class OsaHome(_OSA):
    _icon = "osa-home.png"


class OsaHub(_OSA):
    _icon = "osa-hub.png"


class OsaIcsDrive(_OSA):
    _icon = "osa-ics-drive.png"


class OsaIcsPlc(_OSA):
    _icon = "osa-ics-plc.png"


class OsaIcsThermometer(_OSA):
    _icon = "osa-ics-thermometer.png"


class OsaIdCard(_OSA):
    _icon = "osa-id-card.png"


class OsaImageGeneric(_OSA):
    _icon = "osa-image-generic.png"


class OsaIphone(_OSA):
    _icon = "osa-iphone.png"


class OsaLaptop(_OSA):
    _icon = "osa-laptop.png"


class OsaLifecycle(_OSA):
    _icon = "osa-lifecycle.png"


class OsaLightning(_OSA):
    _icon = "osa-lightning.png"


class OsaMediaFlash(_OSA):
    _icon = "osa-media-flash.png"


class OsaMediaOptical(_OSA):
    _icon = "osa-media-optical.png"


class OsaMediaTape(_OSA):
    _icon = "osa-media-tape.png"


class OsaMobilePda(_OSA):
    _icon = "osa-mobile-pda.png"


class OsaPadlock(_OSA):
    _icon = "osa-padlock.png"


class OsaPrinter(_OSA):
    _icon = "osa-printer.png"


class OsaServerApplication(_OSA):
    _icon = "osa-server-application.png"


class OsaServerDatabase(_OSA):
    _icon = "osa-server-database.png"


class OsaServerDirectory(_OSA):
    _icon = "osa-server-directory.png"


class OsaServerDistribution(_OSA):
    _icon = "osa-server-distribution.png"


class OsaServerFile(_OSA):
    _icon = "osa-server-file.png"


class OsaServerGateway(_OSA):
    _icon = "osa-server-gateway.png"


class OsaServerIdentity(_OSA):
    _icon = "osa-server-identity.png"


class OsaServerMail(_OSA):
    _icon = "osa-server-mail.png"


class OsaServerMedia(_OSA):
    _icon = "osa-server-media.png"


class OsaServerMonitor(_OSA):
    _icon = "osa-server-monitor.png"


class OsaServerProxy(_OSA):
    _icon = "osa-server-proxy.png"


class OsaServerTerminal(_OSA):
    _icon = "osa-server-terminal.png"


class OsaServerWeb(_OSA):
    _icon = "osa-server-web.png"


class OsaServer(_OSA):
    _icon = "osa-server.png"


class OsaSiteBranch(_OSA):
    _icon = "osa-site-branch.png"


class OsaSiteFactory(_OSA):
    _icon = "osa-site-factory.png"


class OsaSiteHeadOffice(_OSA):
    _icon = "osa-site-head-office.png"


class OsaSiteNeighbourhood(_OSA):
    _icon = "osa-site-neighbourhood.png"


class OsaUserAudit(_OSA):
    _icon = "osa-user-audit.png"


class OsaUserBlackHat(_OSA):
    _icon = "osa-user-black-hat.png"


class OsaUserBlueSecuritySpecialist(_OSA):
    _icon = "osa-user-blue-security-specialist.png"


class OsaUserBlueSysadmin(_OSA):
    _icon = "osa-user-blue-sysadmin.png"


class OsaUserBlueTester(_OSA):
    _icon = "osa-user-blue-tester.png"


class OsaUserBlueTie(_OSA):
    _icon = "osa-user-blue-tie.png"


class OsaUserBlue(_OSA):
    _icon = "osa-user-blue.png"


class OsaUserGreenArchitect(_OSA):
    _icon = "osa-user-green-architect.png"


class OsaUserGreenBusinessManager(_OSA):
    _icon = "osa-user-green-business-manager.png"


class OsaUserGreenDeveloper(_OSA):
    _icon = "osa-user-green-developer.png"


class OsaUserGreenOperations(_OSA):
    _icon = "osa-user-green-operations.png"


class OsaUserGreenProjectManager(_OSA):
    _icon = "osa-user-green-project-manager.png"


class OsaUserGreenServiceManager(_OSA):
    _icon = "osa-user-green-service-manager.png"


class OsaUserGreenWarning(_OSA):
    _icon = "osa-user-green-warning.png"


class OsaUserGreen(_OSA):
    _icon = "osa-user-green.png"


class OsaUserLargeGroup(_OSA):
    _icon = "osa-user-large-group.png"


class OsaUserWhiteHat(_OSA):
    _icon = "osa-user-white-hat.png"


class OsaUsersBlueGreen(_OSA):
    _icon = "osa-users-blue-green.png"


class OsaVPN(_OSA):
    _icon = "osa-vpn.png"


class OsaWarning(_OSA):
    _icon = "osa-warning.png"


class OsaWirelessNetwork(_OSA):
    _icon = "osa-wireless-network.png"


# Aliases
